### PR TITLE
Updated the update story

### PR DESCRIPTION
**Pull request by iamfortune**
Added that you can set alternate versions of a story with the management API using group_id

### CODE REVIEW

**Comment by manuelschroederdev** [comment]
Hey @iamfortune,

can you please change the text to:

> Can be used for migrations, updates (e.g. if you changed your component structure), or bulk actions. If you want to publish your story immediately, add the parameter `publish` with the value `1` to the object. In order to set alternate versions of a story, you can set the `group_id` equal to the `group_id` of the story (or stories) that should be the alternate(s).

Also, can you please change the description of the `alternates` parameter to:
> Array of resolved subset of link objects (automatically generated)

**Comment by iamfortune** [comment]
Update made, kindly check it out. @manuelschroederdev

**Comment by manuelschroederdev** [comment]
@iamfortune Thanks!

Could you please also add the `group_id` to the story properties with a short explanation?

Also, for `force_update`, please change the description to: `1` will overwrite a locked story

And for `publish`: `1` will publish the story (must be omitted if publication is not desired)

**Comment by manuelschroederdev** [comment]
Hey @iamfortune can you please make the changes? 🙂

**Comment by iamfortune** [comment]
Hi, @manuelschroederdev I've made the changes as requested, kindly check and merge. 🙂

**Review by manuelschroederdev — APPROVED** [review]

**Pull request merged**
